spring:
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  application:
    name: warehouse
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:warehouse-db
    username: test
    password: test
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        transaction: INFO
        transaction.interceptor: TRACE
        orm.jpa.JpaTransactionManager: DEBUG