spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  profiles:
    active: dev
  application:
    name: warehouse
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/warehouse-db
    username: root
    password: password

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG

app:
  kafka:
    enabled: false
  scheduling:
    enabled: false
    period: 86400000
    priceIncreasePercentage: 10.1
    optimization:
      enabled: false

rest:
  crm-service:
    host: http://localhost:8083
    mock:
      enabled: false
    methods:
      get-uin: /crm
  account-service:
    host: http://localhost:8082
    mock:
      enabled: false
    methods:
      get-account: /account
  currency-service:
    host: http://localhost:8081
    mock:
      enabled: false
    methods:
      get-currency: /api/v1/currencies

kafka:
  bootstrapAddress: localhost:9091
  groupId: group1

  s3:
    accessKey: test
    secretKey: test
    bucketName: warehouse
    region: us-east-1
    path: http://localhost:4566
